import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class DataService {
  icons = [
    'fas fa-address-book',
    'fas fa-address-card',
    'fas fa-ambulance',
    'fas fa-archive',
    'fas fa-asterisk',
    'fas fa-automobile',
    'fas fa-bank',
    'fas fa-bath',
    'fas fa-battery',
    'fas fa-bed',
    'fas fa-beer',
    'fas fa-behance',
    'fas fa-bell',
    'fas fa-bicycle',
    'fas fa-binoculars',
    'fas fa-birthday-cake',
    'fas fa-bitbucket',
    'fas fa-bitcoin',
    'fas fa-black-tie',
    'fas fa-bluetooth',
    'fas fa-bomb',
    'fas fa-book',
    'fas fa-btc',
    'fas fa-bug',
    'fas fa-building',
    'fas fa-bus',
    'fas fa-calculator',
    'fas fa-calendar',
    'fas fa-camera',
    'fas fa-camera-retro',
    'fas fa-car',
    'fas fa-cart-plus',
    'fas fa-certificate',
    'fas fa-chain',
    'fas fa-check',
    'fas fa-child',
    'fas fa-chrome',
    'fas fa-clipboard',
    'fas fa-clock-o',
    'fas fa-clone',
    'fas fa-close',
    'fas fa-cloud',
    'fas fa-cloud-download',
    'fas fa-cloud-upload',
    'fas fa-code',
    'fas fa-coffee',
    'fas fa-columns',
    'fas fa-comments',
    'fas fa-compass',
    'fas fa-compress',
    'fas fa-copy',
    'fas fa-credit-card',
    'fas fa-dashboard',
    'fas fa-database',
    'fas fa-delicious',
    'fas fa-desktop',
    'fas fa-diamond',
    'fas fa-dollar',
    'fas fa-fax',
    'fas fa-feed',
    'fas fa-female',
    'fas fa-firefox',
    'fas fa-gift',
    'fas fa-git',
    'fas fa-github',
    'fas fa-headphones',
    'fas fa-heart',
    'fas fa-magic',
    'fas fa-magnet',
    'fas fa-mobile',
    'fas fa-paste',
    'fas fa-pause',
    'fas fa-paypal',
    'fas fa-pencil',
    'fas fa-phone',
    'fas fa-play',
    'fas fa-save',
    'fas fa-sign-in',
    'fas fa-sign-out',
    'fas fa-spinner',
    'fas fa-star',
    'fas fa-telegram',
    'fas fa-television',
    'fas fa-tree',
    'fas fa-umbrella',
  ];

  getRandomIcon(): string {
    const randomIndex = Math.floor(Math.random() * this.icons.length);
    return this.icons[randomIndex];
  }
}
